version: "3"
services:
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - 18070:8000
    volumes:
      - ./.data/dynamodb:/data
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /data

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "19012:8001"
    environment:
      DYNAMO_ENDPOINT: http://dynamodb:8000

  dynamodb-init:
    image: amazon/aws-cli:latest
    environment:
      # example data: https://docs.aws.amazon.com/ja_jp/cli/latest/userguide/cli-configure-envvars.html
      - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
      - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - DYNAMO_DB_URL=http://dynamodb:8000
    volumes:
      - ./init-dynamodb-local.sh:/init-dynamodb-local.sh
    entrypoint: /init-dynamodb-local.sh
    profiles:
      - init

  s3:
    image: minio/minio
    volumes:
      - ./.data/s3:/data/s3
    ports:
      - 19010:9000
      - 19011:9001
    environment:
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    command: server --console-address :9001 /data/s3

  s3-init:
    image: minio/mc
    depends_on:
      - s3
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add myminio http://s3:9000 AKIAIOSFODNN7EXAMPLE wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb myminio/webdav-serverless;
      /usr/bin/mc policy download myminio/webdav-serverless;
      exit 0;
      "
    profiles:
      - init
